linters-settings:
  golint: {}
  staticcheck: {}
  unused: {}
  govet: {}
  structcheck: {}
  interfacer: {}
  gofmt:
    max-same:
      default: 4
  gocyclo:
    min-complexity: 10
  maligned: {}
  errcheck: {}
  deadcode: {}
  sqlclosecheck: {}
  decorder: {}
  linters-settings: {}
  misspell: {}
  whitespace: {}
  lll: {
      # Max line length, lines longer will be reported.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
      # Default: 120.
      line-length: 120,
      # Tab width in spaces.
      # Default: 1
      tab-width: 4,
    }

linters:
  enable-all: true
  disable:
    - wsl # Ignore warnings about Windows-style line endings
